spring:
  application:
    name: quartzdemo
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9002

eureka:
  client:
    service-url:
      # \u6CE8\u518C\u5230eureka\u670D\u52A1\u53D1\u73B0\u4E2D\u5FC3
      defaultZone: http://localhost:8761/eureka/