spring:
  application:
    name: registry

# 注册中心的默认端口号
server:
  port: 8761

eureka:
  client:
    # 设置eureka 服务器不作为客户端来自我注册
    register-with-eureka: false
  server:
    # 关闭自我保护机制，客户端宕机后，把实例从注册列表中去除
    enable-self-preservation: false
    # 清理注册表定时任务的时间间隔, 默认是60秒
    eviction-interval-timer-in-ms: 5000