spring:
  application:
    # ?????????????????????????ID
    name: registry

# ?????????????????????????????????????8761
server:
  port: 8761

eureka:
  client:
    # eureka??????????????????????????
    register-with-eureka: false